# Add/remove 'critical' label if issue contains the words 'urgent' or 'critical'

extension:tabbs:
  - '\[x\]\ tabbs'
extension:tab-groups-extension:
  - '\[x\]\ tab\ groups\ extension'
extension:tab-multi-selector:
  - '\[x\]\ tab\ multi\-selector'
extension:chrome-tab-renamer:
  - '\[x\]\ chrome\ tab\ renamer'
extension:copy-as-markdown:
  - '\[x\]\ copy\ as\ markdown'
